# print("Hello from lesson 5")
# name = input("What is their name? ")
# age = input("What is their age this year? ")
# personal = input("What would you like to tell them? ")
# print("Happy",age+"th birthday",name+"!",personal+"!")
