# print("My name is Utkarsh")
# print("I am 12 years old")
# print("I attend Singapore American School, or SAS")
# print("If I had $2000, I would put in the bank to get more money in interest")
# print("Wake up and get out of bed.")
# print("Pour milk and cereal into a bowl.")
# print("Eat your breakfast.")
# print("Hello and how are you?")
# print("What is wrong with this")
# print("Why is this not working?")
# print("Why is this not working?")